### ISSUE TITLE
Stuck in reproject_with_depth

### ISSUE THREAD

**Issue by whubaichuan** [alibaba/cascade-stereo#1]
Hi,

when running the cascadeMVSNet, I can get the depth.pfm and pro.pfm.
But once I get into the depth fusion, the code will stuck in line 259 in test.py. So I can't get the final .ply.

**Comment by EugenioTL** [comment]
Hi, I am facing the same issue!
After last iterations I have the last intermediate .ply and then the code stucks without any termination or any final .ply.
Ah, I am actually not using Gipuma.

**Comment by whubaichuan** [comment]
@EugenioTL Hi, maybe you can try Gipuma.
I don't use Gipuma because of no points found. PS: the Gipuma I used is the repo "https://github.com/YoYo000/MVSNet".
Hope to hear about your success.

**Comment by gxd1994** [comment]
> Hi,
> 
> when running the cascadeMVSNet, I can get the depth.pfm and pro.pfm.
> But once I get into the depth fusion, the code will stuck in line 259 in test.py. So I can't get the final .ply.


No problem with me. Is it due to insufficient memory?

**Comment by gxd1994** [comment]
> @EugenioTL Hi, maybe you can try Gipuma.
> I don't use Gipuma because of no points found. PS: the Gipuma I used is the repo "https://github.com/YoYo000/MVSNet".
> Hope to hear about your success.

no points found, because the points are filtered out, you can set num_consistent = 1, and prob_threshold = 0.5

**Comment by EugenioTL** [comment]
> 
> 
> > @EugenioTL Hi, maybe you can try Gipuma.
> > I don't use Gipuma because of no points found. PS: the Gipuma I used is the repo "https://github.com/YoYo000/MVSNet".
> > Hope to hear about your success.
> 
> no points found, because the points are filtered out, you can set num_consistent = 1, and prob_threshold = 0.5

Is there a way to unstuck without using Gipuma? Memory should be enough, actually I am using 1080Ti

**Comment by gxd1994** [comment]
> > > @EugenioTL Hi, maybe you can try Gipuma.
> > > I don't use Gipuma because of no points found. PS: the Gipuma I used is the repo "https://github.com/YoYo000/MVSNet".
> > > Hope to hear about your success.
> > 
> > 
> > no points found, because the points are filtered out, you can set num_consistent = 1, and prob_threshold = 0.5
> 
> Is there a way to unstuck without using Gipuma? Memory should be enough, actually I am using 1080Ti

You can try debugging. Note: Do not use the multirpocessing module first, as it is not easy to catch errors. So you can replace the code in line 463 in the test.py file:
`pcd_filter(testlist, args.num_worker)`  —>  `pcd_filter_worker(testlist)` 
then you may see related error messages

**Comment by EugenioTL** [comment]
> 
> 
> > > > @EugenioTL Hi, maybe you can try Gipuma.
> > > > I don't use Gipuma because of no points found. PS: the Gipuma I used is the repo "https://github.com/YoYo000/MVSNet".
> > > > Hope to hear about your success.
> > > 
> > > 
> > > no points found, because the points are filtered out, you can set num_consistent = 1, and prob_threshold = 0.5
> > 
> > 
> > Is there a way to unstuck without using Gipuma? Memory should be enough, actually I am using 1080Ti
> 
> You can try debugging. Note: Do not use the multirpocessing module first, as it is not easy to catch errors. So you can replace the code in line 463 in the test.py file:
> `pcd_filter(testlist, args.num_worker)` —> `pcd_filter_worker(testlist)`
> then you may see related error messages

Thanks very much, it worked!

**Comment by whubaichuan** [comment]
@EugenioTL How does it works?

**Comment by EugenioTL** [comment]
@whubaichuan I am still not able to perfectly replicate TnT experiments, but I am able to execute the code.
I have also noticed that performances are related with max_width and max_height, such as with other hyperparameters.

**Comment by whubaichuan** [comment]
@EugenioTL Try it "https://github.com/kwea123/CasMVSNet_pl"

**Comment by whubaichuan** [comment]
@EugenioTL Actually, see https://github.com/kysucix/fusibile/issues/9.
You will find the solution to avoid "found no points" in fusible.  It's the problem about the GPU.

**Comment by YuhsiHu** [comment]
Hey, I found the same problem. It would stuck at  'sampled_depth_src = cv2.remap(depth_src, x_src, y_src, interpolation=cv2.INTER_LINEAR)' in test.py. However,  I changed the number of workers to 1 and used GPU 3090, but it did not work. It is weird because I can run it on another computer. Their environments are the same.
