### ISSUE TITLE
How do you understand the 'I' in 'the plane interval I'? thank you !!!

### ISSUE THREAD

**Issue by tjutzdd** [alibaba/cascade-stereo#13]
Hello authors, I can't understand the meaning of the ' I ' from 'Fig3, I is the plane interval'. Can you explain it in detail?

**Comment by kwea123** [comment]
There are D depth planes, and each plane is separated with distance I.
For example `I = 10`, then each plane represents the feature map at distances 10, 20, 30, etc.

**Comment by tjutzdd** [comment]
@kwea123 
Thank you very much for your answer. I know how the 'I' is calculated, but I still don't know its role in cost volume. It seems that the previous cost volume didn't have this interval 'I'. Is this interval 'I' related to the number of feature maps channels? What is the initial interval 'I'?
This interval 'I' is like a new concept here for me, I don't know what it does.
Looking forward to your reply! Thank you!

**Comment by kwea123** [comment]
I is independent of the feature map channels. It is related to accuracy. MVSNet or many other stereo matching is all based on the concept of "creating lots of hypothesis planes, then find the best". It is very similar to the following number guessing game: I have a number between 1 and 100, can you find what it is? You can only ask "Is it between *a* and *b*?".

What MVSNet does: ask if it's between 1 and 2, then 2 and 3, .. until 99 and 100.
This method does: ask if it's between 1 and 10, then 10 and 20, ... until 90 and 100. For example if I answer that it's between 40 and 50, then it guesses if it's between 40 and 42, 42 and 44, etc.

It is exactly what `I` does! The initial I is large to provide only a rough guess, then at the following levels it narrows the range.

Going back to the paper, if you want to know exactly the initial value of `I`, it is `10.6 5.3 2.65` for the three levels from coarse to fine

**Comment by tjutzdd** [comment]
@kwea123 
I see. You are the fastest response I have received. Thank you for your warm help. I focus on stereo matching direction. I haven't paid enough attention to multi-view stereo vision. Once again, I'd like to express my thanks to you. Thank you for your efforts. You're very handsome. Quietly, do you mainly study multi-view stereo vision direction?

**Comment by kwea123** [comment]
No I just started recently (about a month or two ago), I have read some recent deep learning multi-view papers, they all share the same concept (I'm not familiar with traditional methods..), so I think it's quite easy to get started.

**Comment by tjutzdd** [comment]
@kwea123 
Well, thank you very much !!!
