### ISSUE TITLE
question about bias

### ISSUE THREAD

**Issue by kwea123** [alibaba/cascade-stereo#2]
https://github.com/alibaba/cascade-stereo/blob/85803f3e228e19ec94f291fd1a74ac6facf5090c/CasMVSNet/models/module.py#L399-L403

Some layers are with bias and some are not. These layers are not followed by batch normalization, so is there any reason that you set the bias to `False`?

**Comment by gxd1994** [comment]
> https://github.com/alibaba/cascade-stereo/blob/85803f3e228e19ec94f291fd1a74ac6facf5090c/CasMVSNet/models/module.py#L399-L403
> 
> Some layers are with bias and some are not. These layers are not followed by batch normalization, so is there any reason that you set the bias to `False`?

Hi，
You can try set bias = True to retrain the model, I don't think there will be a big difference

**Comment by kwea123** [comment]
Thanks, it's just personal preference then.
