### ISSUE TITLE
Accuracy for Test Data with Colmap

### ISSUE THREAD

**Issue by AbegNext** [alibaba/cascade-stereo#3]
Hello.

I tried this implementation MVSNet+cascade cost volume. It has great results for the DTU dataset. I tried the Tanks and Temples and other private datasets with very bad results. I tried SfM using Colmap, then using the script provided to turn the colmap data into MVSNet data, and then run the algorithm. Do you have recommendations or is there any step I am missing? Does this implementation have problems with big depth differences within a depth map?

**Comment by gxd1994** [comment]
> Hello.
> 
> I tried this implementation MVSNet+cascade cost volume. It has great results for the DTU dataset. I tried the Tanks and Temples and other private datasets with very bad results. I tried SfM using Colmap, then using the script provided to turn the colmap data into MVSNet data, and then run the algorithm. Do you have recommendations or is there any step I am missing? Does this implementation have problems with big depth differences within a depth map?

Hi
1. if you try our provided 

> Hello.
> 
> I tried this implementation MVSNet+cascade cost volume. It has great results for the DTU dataset. I tried the Tanks and Temples and other private datasets with very bad results. I tried SfM using Colmap, then using the script provided to turn the colmap data into MVSNet data, and then run the algorithm. Do you have recommendations or is there any step I am missing? Does this implementation have problems with big depth differences within a depth map?


1. If you try to use the models we provide, you can get good results in the intermediate benchmark tests of tanks and temples. Better results can be obtained if the depth range of each scene is adjusted.
2. When using input from COLMAP SfM, an undistorted image must be used.  COLMAP provides the functionality of undistortion. We have tried many scenes, including large depth ranges, and we can all achieve good results. 

> Hello.
> 
> I tried this implementation MVSNet+cascade cost volume. It has great results for the DTU dataset. I tried the Tanks and Temples and other private datasets with very bad results. I tried SfM using Colmap, then using the script provided to turn the colmap data into MVSNet data, and then run the algorithm. Do you have recommendations or is there any step I am missing? Does this implementation have problems with big depth differences within a depth map?

1. If you try to use the models we provide, you can get good results in the intermediate benchmark tests of tanks and temples. Better results can be obtained if the depth range of each scene is adjusted.
2. When using input from COLMAP SfM, an undistorted image must be used.  COLMAP provides the functionality of undistortion. We have tried many scenes, including large depth ranges, and we can all achieve good results.

**Comment by gxd1994** [comment]
> Hello.
> 
> I tried this implementation MVSNet+cascade cost volume. It has great results for the DTU dataset. I tried the Tanks and Temples and other private datasets with very bad results. I tried SfM using Colmap, then using the script provided to turn the colmap data into MVSNet data, and then run the algorithm. Do you have recommendations or is there any step I am missing? Does this implementation have problems with big depth differences within a depth map?

1. If you try to use the models we provide, you can get good results in the intermediate benchmark tests of tanks and temples. Better results can be obtained if the depth range of each scene is adjusted.
2. When using input from COLMAP SfM, an undistorted image must be used.  COLMAP provides the functionality of undistortion. We have tried many scenes, including large depth ranges, and we can all achieve good results.

**Comment by AbegNext** [comment]
Hi @gxd1994. Thank you for your input. By changing the " depth range" of each scene do you mean the '--numdepth' parameter? If not, can you point out to me where to adjust the depth range? Could it be adjusted by image? I tried COLMAP SfM, and then "colmap2mvsnet.py" script, but as I mentioned, I had poor results. Thanks!

**Comment by gxd1994** [comment]
Hi @AbegNext ,  depth range= depth_max- depht_min.  you can adjust  the parameter of '--interval_scale' , if try COLMAP SFM,  you can try to set this parameter from 0.2-0.5-1.0. 
I suspect the result of COLMAP SFM is not good.

**Comment by AbegNext** [comment]
Thank you @gxd1994 . As I continue my testing, I have gotten excellent results, except those thin elements that are close or far away from the camera won't be reconstructed. As you mentioned, this is directly related to the depth range. I, therefore, have two questions: (1) are the depth range parameters located at the cam.txt files modified somewhere else in the code during execution? ; (2) do you think this network would support at some point the ability to specify a depth range per each pixel instead of per image?

**Comment by gxd1994** [comment]
Hi @AbegNext 
1. Adjust depth range in dataloader file: datasets/general_eval.py
2. Our proposed cascade cost volume achieves good results. One of the reasons is that the depth range of each pixel in our subsequent stages is adaptive.

**Comment by gxd1994** [comment]
Hi @AbegNext 
1.Adjust depth range in dataloader file: datasets/general_eval.py
2.The depth range of each pixel in our subsequent stages is adaptive and determined by the results of the previous stage .

**Comment by kwea123** [comment]
@AbegNext You said you have gotten excellent result, can you share the testing parameters you are using? I had a hard time tuning the parameters, but still can't get acceptable results. Only scenes "Family", "Francis" and "Horse" are good, others are really bad.

**Comment by fanshixiong** [comment]
@kwea123 @AbegNext can you share the testing parameters you are using? I had a hard time tuning the parameters, but still can't get acceptable results.
