### ISSUE TITLE
Selection of number of depths in each level

### ISSUE THREAD

**Issue by kwea123** [alibaba/cascade-stereo#4]
For MVS, why exactly do you choose [48, 32, 8] as the final number of depths in each level?
For the experiments concerning the effect of different number of depths, I can only find Table 7, which compares different combinations like [96, 96], [96, 48, 48], etc. But I cannot find any explanation of how suddenly [48, 32, 8] is chosen or why it is better (for example is [48, 32, 16] better?). Did I miss anything in the paper? Or can you provide a brief explanation here? Thanks.

**Comment by gxd1994** [comment]
we discussed the factors that affect accuracy and memory in section 3.2 of the paper. Number of Hypothesis Planes is the key factor. The larger the number of planes, the higher the accuracy, but the GPU memory will increase. We can adjust these parameters to apply to different situation. For example, we can get more lightweight model by reducing the range quickly and setting fewer planes
