### ISSUE TITLE
Why I can not train the model on 2 Nvidia GTX 1080Ti GPUs with 2 training samples on each GPU?

### ISSUE THREAD

**Issue by chaytonmin** [alibaba/cascade-stereo#7]
I can not train the model on 2 Nvidia GTX 1080Ti GPUs with 2 training samples on each GPU.
And the  GPU process can not be killed.

**Comment by gxd1994** [comment]
I can train the model with batch size 2 using GTX10180ti, maybe you can try the 
high version of pytorch,  i.e. pytorch>=1.2
