### ISSUE TITLE
coarse to fine detach vs. nodetach

### ISSUE THREAD

**Issue by kwea123** [alibaba/cascade-stereo#9]
When doing depth regression using coarse to fine, by default you detach the gradient here:
https://github.com/alibaba/cascade-stereo/blob/85803f3e228e19ec94f291fd1a74ac6facf5090c/CasMVSNet/models/cas_mvsnet.py#L130-L133
It is intuitive, since we don't want the finer level training affect coarser levels, and it is necessary to actually analyze the effect of coarse to fine. But I wonder if the results get better if you don't detach the gradient here? Did you do any experiment, and what is your opinion?

**Comment by gxd1994** [comment]
Hi @kwea123  yes,  `detach` operation can bring better results.
